server:
  port: 8888

spring:
  application:
    name: wcafe-config-server
  cloud:
    config:
      server:
        git:
          uri: classpath:config/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    preferIpAddress: true
    instance-id:
 