spring:
  application:
    name: wcafe-config-server
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/wltn716/msa.git'

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: ["env", "refresh"]