apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 2
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: wltn716/to-order
        env:
        - name: EUREKA_CLUSTER_SERVICES
          valueFrom:
            configMapKeyRef:
              name: eureka-cluster-config
              key: eureka_cluster_services
        - name: HTTPD_PORT
          value: "8005"
        - name: JAVA_OPTS
          value: "-Dspring.profiles.active=dev -Ddatabase.name=order -Dconfig.server=http://config:8888 -Dservice.name=order -Dpackage.name=wcafeOrder"
        resources:
          requests:
            cpu: "150m"
            memory: "128Mi"
        imagePullPolicy: Always # IfNotPresent
        ports:
        - containerPort: 8005
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8005
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8005
          initialDelaySeconds: 30
          timeoutSeconds: 5