version: '3'
services:
  eureka-server:
    image: 'to-eureka-server'
    ports:
      - '8761:8761'
    environment:
      - EUREKA_SERVER_NAME=eureka-server
      - PORT=8761
      
  order:
    image: 'to-order'
    ports:
      - '8005:8005'
    environment:
      - EUREKA_SERVER_NAME=eureka-server
      - EUREKA_SERVER_PORT=8761
      - PORT=8005
    links:
      - eureka-server
      
  product:
    image: 'to-product'
    ports:
      - '8010:8010'
    environment:
      - EUREKA_SERVER_NAME=eureka-server
      - EUREKA_SERVER_PORT=8761
      - PORT=8010
    links:
      - eureka-server 

  web:
    image: 'to-web'
    ports:
      - '8080:8080'
    environment:
      - EUREKA_SERVER_NAME=eureka-server
      - EUREKA_SERVER_PORT=8761
      - PORT=8080
    links:
      - eureka-server 
      
  zuul-api-gateway:
    image: 'to-api-gateway'
    ports:
      - '8090:8090'
    environment:
      - EUREKA_SERVER_NAME=eureka-server
      - EUREKA_SERVER_PORT=8761
      - PORT=8090
    links:
      - eureka-server
      - order
      - product