debug: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8000
spring:
  application:
    name: wcafe-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: asdf1234
    url: jdbc:mysql://localhost:3306/user?useSSL=false&serverTimezone=UTC
    username: root
  mustache:
    suffix: .html
