spring:
  application:
    name: wcafe-web
  mustache:
    suffix: .html
  
    
server:  port: 8080 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
 
debug: true