apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - name: config
        image: wltn716/to-config-server:latest
        env:
        - name: HTTPD_PORT
          value: "8888"
        resources:
          requests:
            cpu: "150m"
            memory: "128Mi"
        imagePullPolicy: Always # IfNotPresent
        ports:
        - containerPort: 8888
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 30
          timeoutSeconds: 5

