apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  serviceName: eureka
  replicas: 2
  minReadySeconds: 30
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: wltn716/to-eureka-server:latest
        imagePullPolicy: Always # IfNotPresent
        env:
        - name: EUREKA_CLUSTER_SERVICES
          valueFrom:
            configMapKeyRef:
              name: eureka-cluster-config
              key: eureka_cluster_services
        - name: HTTPD_PORT
          value: "8761"
        - name: JAVA_OPTS
          value: "-Dspring.profiles.active=dev -Deureka.hostname=eureka"
        resources:
          requests:
            cpu: "150m"
            memory: "128Mi"
        ports:
        - containerPort: 8761
        livenessProbe:
          httpGet:
            path: /
            port: 8761
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8761
          initialDelaySeconds: 30
          timeoutSeconds: 5