apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 2
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: wltn716/to-product
        env:
        - name: EUREKA_CLUSTER_SERVICES
          valueFrom:
            configMapKeyRef:
              name: eureka-cluster-config
              key: eureka_cluster_services
        - name: HTTPD_PORT
          value: "8010"
        - name: JAVA_OPTS
          value: "-Dspring.profiles.active=dev -Ddatabase.name=product -Dconfig.server=http://config:8888 -Dservice.name=product -Dpackage.name=wcafeProduct"
        resources:
          requests:
            cpu: "150m"
            memory: "128Mi"
        imagePullPolicy: Always # IfNotPresent
        ports:
        - containerPort: 8010
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 5