apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 2
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: wltn716/to-auth-server
        env:
        - name: EUREKA_CLUSTER_SERVICES
          valueFrom:
            configMapKeyRef:
              name: eureka-cluster-config
              key: eureka_cluster_services
        - name: HTTPD_PORT
          value: "8090"
        - name: JAVA_OPTS
          value: "-Djava.security.egd=file:/dev/./urandom -Dfile.encoding=UTF8 -Dclient.encoding.override=UTF-8 -Duser.timezone=GMT+09:00 -Dsun.java2d.opengl=false -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Dspring.profiles.active=dev -Ddatabase.name=oauth2 -Dconfig.server=http://config:8888 -Dservice.name=auth"
        resources:
          requests:
            cpu: "150m"
            memory: "128Mi"
        imagePullPolicy: Always # IfNotPresent
        ports:
        - containerPort: 8095
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8095
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8095
          initialDelaySeconds: 30
          timeoutSeconds: 5