eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.hostname:localhost}:8761/eureka/
server:
  port: 8761
spring:
  application:
    name: wcafe-eureka-server
